### ISSUE TITLE
Can't do arithmetic on nats

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#246] opened 2018-06-28 14:03 UTC
You can't do arithmetic on `nat`s, only `float`s, which means `1.+1.` is ok but `1+1` is an error.

**Comment by jeromesimeon** [comment] 2018-06-28 20:16
This is a duplicate of #159

**Closed by jeromesimeon** 2018-06-28 20:16 UTC
Labels: backend

**Comment by kach** [comment] 2018-06-28 20:36
(Self note: you can use `+i` as an infix op for math on nats…)
